  head
    meta http-equiv="content-Type" content="text/html; charset=UTF-8"
    meta name="viewport" content="width=device-width,initial-scale=1.0"
    title #{title}
    link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css"
    link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css"
    link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css"
    css:
      code, pre {white-space: pre-wrap; font-size: 0.5em;}
      .btn-group { margin-bottom: 0.2em; }
